version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_dev_17
    environment:
      POSTGRES_DB: registro_gasto
      POSTGRES_USER: postgres-registro-gasto
      POSTGRES_PASSWORD: ZSWEDzx24#
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: