spring.application.name=gastos-fianceiros

# Configuração de conexão com o banco de dados
spring.datasource.url={DB_URL}
spring.datasource.username={DB_USER}
spring.datasource.password={DB_PASSWORD}

# Configuração do Hibernate (Opcional nesta fase inicial)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

