spring.application.name=gastos-fianceiros

# Configuração de conexão com o banco de dados
# O uso de '${VAR:default}' impede que a aplicação quebre se a variável não estiver no ambiente
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
# server.port=${SERVER_PORT:5000}

# # Configurações de JPA e Hibernate
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT_SERVE:5001}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# O dialeto MySQLDialect genérico funciona bem para MySQL 8+. 
# Se estiver em versões muito antigas, o MySQL5Dialect é preferível.
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flyway desligado conforme sua preferência
spring.flyway.enabled=false

# Chave secreta para assinatura dos tokens JWT (pode ser qualquer texto seguro de sua preferência)
api.security.token.secret=${JWT_SECRET:gQo5dUHNi5AImZBsyZMAdf9rJMQOk5vJ3CRAR5jMn0g=}